# Generated by Django 5.0.6 on 2024-06-19 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +7 (000)-000-0000', regex='^\\+7 \\(\\d{3}\\)-\\d{3}-\\d{4}$')], verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Изображение')),
                ('email', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный email адрес.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')], verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
    ]
