# Generated by Django 5.0.6 on 2024-06-20 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goods", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания заказа"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть в формате +7 (000)-000-0000",
                                regex="^\\+7 \\(\\d{3}\\)-\\d{3}-\\d{4}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "requires_delivery",
                    models.BooleanField(
                        default=False, verbose_name="Требуется доставка"
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Адрес доставки"
                    ),
                ),
                (
                    "payment_on_get",
                    models.BooleanField(
                        default=False, verbose_name="Оплата при получении"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Оплачено"),
                ),
                (
                    "status",
                    models.CharField(
                        default="В разработке",
                        max_length=50,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="Order_dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=7, verbose_name="Цена"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата продажи"
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="goods.dishes",
                        verbose_name="Блюдо",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ блюда",
                "verbose_name_plural": "Заказы блюд",
                "db_table": "order_dish",
            },
        ),
    ]
